### ISSUE TITLE
Off Centered Screen When FPS Unlocker Is Being Used On Macbook

### ISSUE THREAD

**Issue by tjw1245** [lanylow/rbxfpsunlocker-osx#264] opened 2023-12-03 15:54 UTC
When using fps unlocker on Macbook with a 2nd display its off centered and really zoomed in and wont click on what your cursor is on. Someone please answer this already. 
<img width="1336" alt="Untitled" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/152564491/c0acad2e-a079-44d9-ab9c-c920f5e43750">

**Comment by Ritish-Mithiradas** [comment] 2023-12-03 21:39
same issue here

**Comment by hello2340** [comment] 2023-12-05 23:48
@lanylow i still got this issue

**Comment by lanylow** [comment] 2023-12-10 12:57
Duplicate of #256.

**Closed as completed by lanylow** 2023-12-10 12:57 UTC
