### ISSUE TITLE
Im so laggy scince i installed

### ISSUE THREAD

**Issue by Xert-max** [lanylow/rbxfpsunlocker-osx#260] opened 2023-11-26 23:33 UTC
I need to uninstall its been so laggy scince in unsinstalled and i need to know how to remove it!

**Comment by CheekyCodes** [comment] 2023-12-02 07:46
reinstall roblox

**Comment by lanylow** [comment] 2023-12-10 12:56
Duplicate of #257.

**Closed as completed by lanylow** 2023-12-10 12:56 UTC
