### ISSUE TITLE
I have a confusing issue

### ISSUE THREAD

**Issue by oasonlol** [lanylow/rbxfpsunlocker-osx#100] opened 2022-11-04 05:38 UTC
I have an issue with the fps unlocked I got Roblox open but it still says logic error failed to get Roblox info make sure Roblox is open even though I got Roblox open

**Comment by oasonlol** [comment] 2022-11-04 05:38
can somebody help me to fix this problem

**Comment by lanylow** [comment] 2022-11-04 06:35
Duplicate of #93.

**Closed** 2022-11-04 06:35 UTC
Labels: duplicate
