### ISSUE TITLE
Aspect Ratio and Zoom all broken after Roblox update on November 30th

### ISSUE THREAD

**Issue by rithkott** [lanylow/rbxfpsunlocker-osx#262] opened 2023-12-01 23:01 UTC
Installing the fps unlocked makes the Roblox app appear zoomed in and the button positions are all wrong, as if its displayed in the wrong resolution

**Comment by Elijahb04** [comment] 2023-12-02 04:05
I'm experiencing the same problem.

**Comment by CheekyCodes** [comment] 2023-12-02 07:45
can replicate

**Comment by hello2340** [comment] 2023-12-02 19:47
same issues

**Comment by Ritish-Mithiradas** [comment] 2023-12-03 21:39
same issue

**Comment by tjw1245** [comment] 2023-12-05 03:54
same thing here

**Comment by tjw1245** [comment] 2023-12-05 03:55
@lanylow please help us fix this

**Comment by Juicedu** [comment] 2023-12-05 22:52
Hi I've noticed a lot of display issues, can anyone provide me a screenshot because I am all fine here running 120 FPS and regular display. If your curious I have a late 2015 iMac Retina, would like to know if you guys have older models (likely not the case of issue).

**Comment by tjw1245** [comment] 2023-12-05 22:58
Its for 2nd displays

**Comment by lanylow** [comment] 2023-12-10 12:57
Duplicate of #256.

**Closed as completed by lanylow** 2023-12-10 12:57 UTC
